### PR TITLE
Notes Option

### PR DESCRIPTION
**Pull request by kmanalo**
@rlyon 

I'm not sure if your version of Torque has this, but we use the 'notes' attribute quite frequently for administering nodes.

Example:

```
pbsnodes node001 -N "Bad Hard Drive"

pbsnodes -ln # list the nodes with notes where -l is usually offline  or down nodes

pbsnodes node001 -N "" # clear the note
```

I wanted to get your feedback on this, otherwise I plan on just keeping this in my fork.  I tried my best to stay true to the original, and hence the original tests should be preserved (as Travis CI says).  I probably need to add some tests myself, given your interest.

General implementation was done by leveraging 'N' as another state label, and using the filter methods accordingly.

The new options are listed here:

<pre>
Usage: qhost [options] [optional-node-regex]

Options:
  -h, --help            show this help message and exit
  -c, --color           turn on colorized output
  -j, --jobs            show job information
  -J JOBID, --jobid=JOBID
                        only show nodes used by the specified job ID
  -n, --ntype           show node type information
  <b>-N, --note            show note information</b>
  -p, --properties      show node properties
  -a, --all             show jobs, node properties, and type
  -v, --version         print version and exit
  -s STATE, --state=STATE
                        filter nodes by state; valid state characters are F
                        (free), O (offline), D (down), R (reserve), E (job-
                        exclusive), S (job-sharing), B (busy), T (time-
                        shared), U (state-unknown), and N (has-note).
  <b>-S SUBSET, --subset=SUBSET
                        same as 'state' above, but matches 'any' condition</b>
  -X XMLFILE, --xmlfile=XMLFILE
                        use an XML file containing the pbsnodes output instead
                        of pbsnodes.
</pre>

A capital N provides note information (stashed under <note>This is a note</node> tags)

But the exact state match was not providing what I was intending for so, therefore, I capitalized the 'S' option to get an 'any' state match.

Some use cases:
```
qhost -X test/output/output_06_note.xml -S O
qhost -X test/output/output_06_note.xml -S N
qhost -X test/output/output_06_note.xml -N
```

Note that this should not break anything (at least it hasn't broke any tests...), and notes are clearly optional attributes.

### CODE REVIEW

**Comment by rlyon** [comment]
Hi!  We use those as well but not all that often.  

I'm not so keen on mixing the notes into the state as it doesn't logically seem to fit there as it is not really a state but a notice of inforamtion.  I could warm to the idea, so I'll consider it.  The '-s' should have been already matching 'any' of the requested states (at least that's what it does right now), so I'll need to look at that one later.  What was the issue you were seeing with the state option or what was the expected behavior?

**Comment by kmanalo** [comment]
Here's an example

```
./bin/qhost -c -s O # only those that are offline
   CPU GPU MEMTOT   MEMUSE   JOBS SLOT LOAD    STATE   
--------------------------------------------------------
   8       35.0G    1.7G     0    0    0.23   |  O      
   8       29.3G    1.6G     0    0    0.18   |  O      
./bin/qhost -c -s D # only 'down' state, usually none because offline & down are buddies
   CPU GPU MEMTOT   MEMUSE   JOBS SLOT LOAD    STATE   
--------------------------------------------------------
./bin/qhost -c -s DOC # intersection of offline/down states, this includes
   CPU GPU MEMTOT   MEMUSE   JOBS SLOT LOAD    STATE   
--------------------------------------------------------
   20      0.0K     0.0K     0    0    0      |  OD     
   8       0.0K     0.0K     0    0    0      |  OD     
   8       0.0K     0.0K     0    0    0      |  OD     
   8       0.0K     0.0K     0    0    0      |  OD     
   8       0.0K     0.0K     0    0    0      |  OD     
   8       35.0G    1.6G     0    0    0.64   |  OD     
   8       35.0G    1.7G     0    0    0.11   |  O      
   8       29.3G    1.6G     0    0    0.18   |  O      
   8   2   0.0K     0.0K     0    0    0      |  OD     
   8       0.0K     0.0K     0    0    0      |  OD     
   16      0.0K     0.0K     0    0    0      |  OD     
   16      0.0K     0.0K     0    0    0      |  OD 
```

The subset match would yield
```
./bin/qhost -c -S O # give me 'any' with an offline state
 OS      CPU GPU MEMTOT   MEMUSE   JOBS SLOT LOAD    STATE   
--------------------------------------------------------------
         20      0.0K     0.0K     0    0    0      |  OD     
         8       0.0K     0.0K     0    0    0      |  OD     
         8       0.0K     0.0K     0    0    0      |  OD     
         8       0.0K     0.0K     0    0    0      |  OD     
         8       0.0K     0.0K     0    0    0      |  OD     
 linux   8       35.0G    1.6G     0    0    0.64   |  OD     
 linux   8       35.0G    1.7G     0    0    0.08   |  O      
 linux   8       29.3G    1.6G     0    0    0.0    |  O      
         8   2   0.0K     0.0K     0    0    0      |  OD     
 linux   8       35.0G    1.8G     3    8    3.88   |  OD E   
         8       0.0K     0.0K     0    0    0      |  OD     
         16      0.0K     0.0K     0    0    0      |  OD     
         16      0.0K     0.0K     0    0    0      |  OD     
./bin/qhost -c -S D # give me any with a 'down' state
 OS      CPU GPU MEMTOT   MEMUSE   JOBS SLOT LOAD    STATE   
--------------------------------------------------------------
         20      0.0K     0.0K     0    0    0      |  OD     
         8       0.0K     0.0K     0    0    0      |  OD     
         8       0.0K     0.0K     0    0    0      |  OD     
         8       0.0K     0.0K     0    0    0      |  OD     
         8       0.0K     0.0K     0    0    0      |  OD     
 linux   8       35.0G    1.6G     0    0    0.64   |  OD     
         8   2   0.0K     0.0K     0    0    0      |  OD     
 linux   8       35.0G    1.8G     3    8    3.88   |  OD E   
         8       0.0K     0.0K     0    0    0      |  OD     
         16      0.0K     0.0K     0    0    0      |  OD     
         16      0.0K     0.0K     0    0    0      |  OD     
./bin/qhost -c -S DO # give me anything with the combo 'OD' state
 OS      CPU GPU MEMTOT   MEMUSE   JOBS SLOT LOAD    STATE   
--------------------------------------------------------------
         20      0.0K     0.0K     0    0    0      |  OD     
         8       0.0K     0.0K     0    0    0      |  OD     
         8       0.0K     0.0K     0    0    0      |  OD     
         8       0.0K     0.0K     0    0    0      |  OD     
         8       0.0K     0.0K     0    0    0      |  OD     
 linux   8       35.0G    1.6G     0    0    0.64   |  OD     
         8   2   0.0K     0.0K     0    0    0      |  OD     
 linux   8       35.0G    1.8G     3    8    3.88   |  OD E   
         8       0.0K     0.0K     0    0    0      |  OD     
         16      0.0K     0.0K     0    0    0      |  OD     
         16      0.0K     0.0K     0    0    0      |  OD     
```

I think both are kind of useful, but I think the latter is helpful in getting the catchall, as you would want to match anything in the 'down' or 'offline' state, in most instances.  

But the naming needs improvement, perhaps  (-s/--state-match) (-S/--state-any) would be clearer?

**Comment by kmanalo** [comment]
Having clearer thoughts, how about this?

I think having an option like (-N optional=show), and moving the weird state 'N' business out would take care of it, so no more '-S N'.  

I'm assuming this can be handled by OptionParse, having `-N` and also, more importantly `-N show` where we filter anything having a note separately.  So basically a separate filter method for the note tags.

Because the notes is more like the gpu tag attribute, clearly optional, and we can corral the idea separate from the states.

**Comment by kmanalo** [comment]
In optparse to have an option that has a boolean boolean (note/note-only):

http://stackoverflow.com/questions/5962890/python-option-parser-boolean-flag-with-optional-parameters
https://docs.python.org/2/library/optparse.html#callback-example-6-variable-arguments

I don't know if we have to take it that far, but what I've done is added -N and --NO options for displaying notes, for now

**Comment by rlyon** [comment]
@kmanalo, I see! (lightbulb turns on)  Actually the expected behavior of the state option was to do what your subset is doing, so the fact that it's not is actually a bug, that's why I was confused.  So I think what we could do is set up state to do what your subset does and then add an 'exclusive' boolean option that could be used with state to only show exact matches.

I've been slammed at work so I'll have some time to take a look over your changes over the weekend.  Thanks!

**Comment by kmanalo** [comment]
@rlyon Cool! This does mean that some of the unit test outputs will require some adjustments... BTW, 'exclusive' is a better naming convention.

**Comment by kmanalo** [comment]
I think your last version covers the above issues so closing.

**Pull request closed without merging**
