### PR TITLE
Weird reporting in job & slots, one-line fix, Addresses #17

### PR DESCRIPTION
**Pull request by kmanalo**
This is my working version but it definitely breaks some tests.

@rlyon you may want to check this fix with your systems and see if the reporting is right

### CODE REVIEW

**Comment by rlyon** [comment]
Could you send me an Xml dump of the output that you are seeing the issue with?  I've not seen that behavior and I'm testing for some of those cases.

**Comment by kmanalo** [comment]
Actually, the `output_05.xml` file covers this issue, as the result should have been
```
NODE               OS      CPU GPU MEMTOT   MEMUSE   JOBS SLOT LOAD    STATE
--------------------------------------------------------------------------------
node100            linux   32      137.6G   82.0G    3    32   41.81  |  OD E
```

instead of 
```
NODE               OS      CPU GPU MEMTOT   MEMUSE   JOBS SLOT LOAD    STATE
--------------------------------------------------------------------------------
node100            linux   32      137.6G   82.0G    1    1    41.81  |  OD E```
```

**Comment by rlyon** [comment]
I guess I should have asked this sooner, but what flavor of pbs are you using?

**Comment by kmanalo** [comment]
Version: 4.2.6.1

**Comment by kmanalo** [comment]
I read version in my mind :) We are using Moab/torque.

**Comment by rlyon** [comment]
Ah, newer version than what I've been running.  It must not have the trailing space after the commas in the xml output.  I think that the cleaner/clearer way to solve that one would be to modify the the job handler:

```python
def handle_node_jobs(self, node):
    data = self.getText(node.childNodes).split(',')
    return map(lambda x: x.lstrip(), data)
```
This way the handler function itself will always return the same job id format regardless of what is coming in.  It also has the added benefit of saving a few cycles because the job id's are being stripped as the new array is being built.

Let me know what you think
-
Rob

**Comment by rlyon** [comment]
Oops, I'm not yelling really.  I'm not sure what happened there

**Comment by kmanalo** [comment]
That is cleaner I will make that change

**Comment by kmanalo** [comment]
Don't know why I didn't see the split there, thanks for pointing it out + the cleaner application.  

One last thing the 'run.py' is reporting errors, what do you reccommend?

**Comment by rlyon** [comment]
Great!  Merging it now.

**Pull request merged**
